[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[env]
CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR = "true"

[tools]
"cargo:zizmor" = "latest"
"gem:teamocil" = "latest"
"npm:@anthropic-ai/claude-code" = "2.0.51"
"npm:@auth0/auth0-mcp-server" = "latest"
"npm:@browsermcp/mcp" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@gsong/ccmcp" = "latest"
"npm:@mariozechner/claude-trace" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@netlify/mcp" = "latest"
"npm:@openai/codex" = "latest"
"npm:@perplexity-ai/mcp-server" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:ccstatusline" = "latest"
"npm:ccusage" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:mcp-remote" = "latest"
"npm:prettier" = "latest"
"npm:repomix" = "latest"
"npm:svgo" = "latest"
"npm:task-master-ai" = "latest"
"npm:tldr" = "latest"
"pipx:crawl4ai" = "latest"
"pipx:files-to-prompt" = "latest"
"pipx:markitdown" = { version = "latest", extras = "all" }
"pipx:speedtest-cli" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:titlecase" = "latest"
ast-grep = "latest"
bun = "latest"
direnv = "latest"
dive = "latest"
eza = "latest"
hadolint = "latest"
lazydocker = "latest"
lua = "5.1"
node = "lts"
pnpm = "latest"
python = ["3.14", "3.13", "3.12", "3.11", "3.10"]
ruby = "3"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
tree-sitter = "latest"
uv = "latest"
